export const CATEGORIES: any[] = [
    {id: 'demanda', label: 'DEMANDA'},
    {id: 'generacion', label: 'GENERACION'},
    {id: 'almacenamiento', label: 'ALMACENAMIENTO'},
    {id: 'intercambios', label: 'INTERCAMBIOS'},
    {id: 'balance', label: 'BALANCE'},
    {id: 'mercados', label: 'MERCADOS'},
    {id: 'transporte', label: 'TRANSPORTE'}
]

export const WIDGETS: any[] = [
    {id: 'evolucion', label: 'EVOLUCION', categoryId: 'demanda'},
    {id: 'variacion-componentes', label: 'VARIACION_COMPONENTES', categoryId: 'demanda'},
    {id: 'variacion-componetes-movil', label: 'VARIACION_COMPONENTES_MOVIL', categoryId: 'demanda'},
    {id: 'ire-general', label: 'IRE_GENERAL', categoryId: 'demanda'},
    {id: 'ire-general-anual', label: 'IRE_GENERAL_ANUAL', categoryId: 'demanda'},
    {id: 'ire-general-movil', label: 'IRE_GENERAL_MOVIL', categoryId: 'demanda'},
    {id: 'ire-indusrial-anual', label: 'IRE_INDUSTRIAL_ANUAL', categoryId: 'demanda'},
    {id: 'ire-industrial-movil', label: 'IRE_INDUSTRIAL_MOVIL', categoryId: 'demanda'},
    {id: 'ire-servicios', label: 'IRE_SERVICIOS', categoryId: 'demanda'},
    {id: 'ire-servicios-anual', label: 'IRE_SERVICIOS_ANUAL', categoryId: 'demanda'},
    {id: 'ire-servicios-movil', label: 'IRE_SERVICIOS_MOVIL', categoryId: 'demanda'},
    {id: 'ire-otras', label: 'IRE_OTRAS', categoryId: 'demanda'},
    {id: 'ire-otras-anual', label: 'IRE_OTRAS_ANUAL', categoryId: 'demanda'},
    {id: 'ire-otras-movil', label: 'IRE_OTRAS_MOVIL', categoryId: 'demanda'},
    {id: 'demanda-maxima-diaria', label: 'DEMANDA_MAXIMA_DIARIA', categoryId: 'generacion'},
    {id: 'variacion-maxima-horaria', label: 'VARIACION_MAXIMA_HORARIA', categoryId: 'generacion'},
    {id: 'perdidas-transporte', label: 'PERDIDAS_TRANSPORTE', categoryId: 'generacion'},
    {id: 'potencia-maxima-instantanea', label: 'POTENCIA_MAXIMA_INSTANTANEA', categoryId: 'generacion'},
    {id: 'variacion-demanda', label: 'VARIACION_DEMANDA', categoryId: 'generacion'},
    {id: 'potencia-maxima-instantanea-variacion', label: 'POTENCIA_MAXIMA_INSTANTANEA_VARIACION', categoryId: 'generacion'},
    {id: 'potencia-maxima-instantanea-variacion-historico', label: 'POTENCIA_MAXIMA_INSTANTANEA_VARIACION_HISTORICO', categoryId: 'generacion'},
    {id: 'demanda-tiempo-real', label: 'DEMANDA_TIEMPO_REAL', categoryId: 'generacion'},
    {id: 'variacion-componentes-anual', label: 'VARIACION_COMPONENTES_ANUAL', categoryId: 'generacion'},
    {id: 'estructura-generacion', label: 'ESTRUCTURA_GENERACION', description: 'ESTRUCTURA_GENERACION_DESC', categoryId: 'generacion'},
    {id: 'evolucion-renovable-no-renovable', label: 'EVOLUCION_RENOVABLE_NO_RENOVABLE', categoryId: 'generacion'},
    {id: 'estructura-renovables', label: 'ESTRUCTURA_RENOVABLES', categoryId: 'generacion'},
    {id: 'estructura-generacion-emisiones-asociadas', label: 'ESTRUCTURA_GENERACION_EMISIONES_ASOCIADAS', categoryId: 'generacion'},
    {id: 'evolucion-estructura-generacion-emisiones-asociadas', label: 'EVOLUCION_ESTRUCTURA_GENERACION_EMISIONES_ASOCIADAS', categoryId: 'generacion'},
    {id: 'no-renovables-detalle-emisiones-CO2', label: 'NO_RENOVABLES_DETALLE_EMISIONES_CO2'},
    {id: 'maxima-renovable', label: 'MAXIMA_RENOVABLE', categoryId: 'generacion'},
    {id: 'potencia-instalada', label: 'POTENCIA_INSTALADA', categoryId: 'generacion'},
    {id: 'maxima-renovable-historico', label: 'MAXIMA_RENOVABLE_HISTORICO', categoryId: 'generacion'},
    {id: 'maxima-sin-emisiones-historico', label: 'MAXIMA_SIN_EMISIONES_HISTORICO', categoryId: 'generacion'},
    {id: 'energia-almacenamiento', label: 'ENERGIA_ALMACENAMIENTO', categoryId: 'almacenamiento'},
    {id: 'potencia_instalada', label: 'POTENCIA_INSTALADA', categoryId: 'almacenamiento'},
    {id: 'francia-frontera', label: 'FRANCIA_FRONTERA', categoryId: 'intercambios'},
    {id: 'portugal-frontera', label: 'PORTUGAL_FRONTERA', categoryId: 'intercambios'},
    {id: 'marruecos-frontera', label: 'MARRUECOS_FRONTERA', categoryId: 'intercambios'},
    {id: 'andorra-frontera', label: 'ANDORRA_FRONTERA', categoryId: 'intercambios'},
    {id: 'lineas-francia', label: 'LINEAS_FRANCIA', categoryId: 'intercambios'},
    {id: 'lineas-portugal', label: 'LINEAS_PORTUGAL', categoryId: 'intercambios'},
    {id: 'lineas-marruecos', label: 'LINEAS_MARRUECOS', categoryId: 'intercambios'},
    {id: 'lineas-andorra', label: 'LINEAS_ANDORRA', categoryId: 'intercambios'},
    {id: 'francia-frontera-programdas', label: 'FRANCIA_FRONTERA_PROGRAMDAS', categoryId: 'intercambios'},
    {id: 'portugal-frontera-programdas', label: 'PORTUGAL_FRONTERA_PROGRAMDAS', categoryId: 'intercambios'},
    {id: 'marruecos-frontera-programdas', label: 'MARRUECOS_FRONTERA_PROGRAMDAS', categoryId: 'intercambios'},
    {id: 'andorra-frontera-programdas', label: 'ANDORRA_FRONTERA_PROGRAMDAS', categoryId: 'intercambios'},
    {id: 'enlace-baleares', label: 'ENLACE_BALEARES', categoryId: 'intercambios'},
    {id: 'frontera-fisicos', label: 'FRONTERA_FISICOS', categoryId: 'intercambios'},
    {id: 'todas-fronteras-fisicos', label: 'TODAS_FRONTERAS_FISICOS', categoryId: 'intercambios'},
    {id: 'frontera-programados', label: 'FRONTERA_PROGRAMADOS', categoryId: 'intercambios'},
    {id: 'todas-fronteras-programdados', label: 'TODAS_FRONTERAS_PROGRAMADADOS', categoryId: 'intercambios'},
    {id: 'energia-no-suministrada-end', label: 'ENERGIA_NO_SUMINISTRADA_ENS', categoryId: 'transporte'},
    {id: 'indice-indisponibilidad', label: 'INDICE_INDISPONIBILIDAD', categoryId: 'transporte'},
    {id: 'tiempo-interrupcion-medio-tim', label: 'TIEMPO_INTERRUPCION_MEDIO_TIM', categoryId: 'transporte'},
    {id: 'kilometros-lineas', label: 'KILOMETROS_LINEAS', categoryId: 'transporte'},
    {id: 'indice-disponibilidad', label: 'INDICE_DISPONIBILIDAD', categoryId: 'transporte'},
    {id: 'numero-cortes', label: 'NUMERO_CORTES', categoryId: 'transporte'},
    {id: 'ens-tim', label: 'ENS_TIM', categoryId: 'transporte'},
    {id: 'indice-disponibilidad-total', label: 'INDICE_DISPONIBILIDAD_TOTAL', categoryId: 'transporte'},
    {id: 'balance-electrico', label: 'BALANCE_ELETRICO', categoryId: 'balance'},
    {id: 'componentes-precio-energia-cierre-desglose', label: 'COMPONENTES_PRECIO_ENERGIA_CIERRE_DESGLOSE', categoryId: 'mercados'},
    {id: 'componentes-precio', label: 'COMPONENTES_PRECIO', categoryId: 'mercados'},
    {id: 'energia-gestionada-servicios-ajuste', label: 'ENERGIA_GESTIONADA_SERVICIOS_AJUSTE', categoryId: 'mercados'},
    {id: 'energia-restricciones', label: 'ENERGIA_RESTRICCIONES', categoryId: 'mercados'},
    {id: 'precios-restricciones', label: 'PRECIOS_RESTRICCIONES', categoryId: 'mercados'},
    {id: 'reserva-potencia-adicional', label: 'RESERVA_POTENCIA_ADICIONAL', categoryId: 'mercados'},
    {id: 'banda-regulacion-secundaria', label: 'BANDA_REGULACION_SECUNDARIA', categoryId: 'mercados'},
    {id: 'energia-precios-regulacion-secundaria', label: 'ENERGIA_PRECIOS_REGULACION_SECUNDARIA', categoryId: 'mercados'},
    {id: 'energia-precios-regulacion-terciaria', label: 'ENERGIA_PRECIOS_REGULACION_TERCIARIA', categoryId: 'mercados'},
    {id: 'energia-precios-gestion-desvios', label: 'ENERGIA_PRECIOS_GESTION_DESVIOS', categoryId: 'mercados'},
    {id: 'coste-servicios-ajuste', label: 'COSTE_SERVICIOS_AJUSTE', categoryId: 'mercados'},
    {id: 'volumen-energia-servicios-ajuste-variacion', label: 'VOLUMEN_ENERGIA_SERVICIOS_AJUSTE_VARIACION', categoryId: 'mercados'},
    {id: 'precios-mercados-tiempo-real', label: 'PRECIOS_MERCADOS_TIEMPO_REAL', categoryId: 'mercados'},
    {id: 'energia-precios-ponderados-gestion-desvios-before', label: 'ENERGIA_PRECIOS_PONDERADOS_GESTION_DESVIOS_BEFORE', categoryId: 'mercados'},
    {id: 'energia-precios-ponderados-gestion-desvios', label: 'ENERGIA_PRECIOS_PONDERADOS_GESTION_DESVIOS', categoryId: 'mercados'},
    {id: 'energia-precios-ponderados-gestion-desvios-after', label: 'ENERGIA_PRECIOS_PONDERADOS_GESTION_DESVIOS_AFTER', categoryId: 'mercados'},                 
]    

export const GEO_TRUNCS: any[] = [
    {id: 'electric_system', label: 'ELECTRIC_SYSTEM'},
]

export const GEO_TYPES: any[] = [
    {id: 'sistema_electrico', label: 'SISTEMA_ELECTRICO'},
    {id: 'comunidades_autonomas', label: 'COMUNIDADES_AUTONOMNAS'}
]

export const GEO_LIMITS: any[] = [
    {id: 'peninsular', label: 'PENINSULAR', geoId: 8741},
    {id: 'canarias', label: 'CANARIAS', geoId: 8742},
    {id: 'baleares', label: 'BALEARES', geoId: 8743},
    {id: 'ceuta', label: 'CEUTA', geoId: 8744},
    {id: 'melilla', label: 'MELILLA', geoId: 8745},
    {id: 'ccaa', label: 'CCAA', regions: [
        { id: "todas", label: "Todas las comunidades", geoId: 4 },
        { id: "andalucia", label: "Andalucía", geoId: 4 },
        { id: "aragon", label: "Aragón", geoId: 5 },
        { id: "cantabria", label: "Cantabría", geoId: 6 },
        { id: "castilla_mancha", label: "Castilla la Mancha", geoId: 7 },
        { id: "castilla_leon", label: "Castilla León", geoId: 8 },
        { id: "cataluna", label: "Cataluña", geoId: 9},
        { id: "pais_vasco", label: "País Vasco", geoId: 10 },
        { id: "asturias", label: "Principado de Asturias", geoId: 11 },
        { id: "comunidad_ceuta", label: "Comunidad de Ceuta", geoId: 8744 },
        { id: "comunidad_melilla", label: "Comunidad de Melilla", geoId: 8745 },
        { id: "comunidad_madrid", label: "Comunidad de Madrid", geoId: 13 },
        { id: "comunidad_navarra", label: "Comunidad de Navarra", eoId: 14 },
        { id: "comunidad_valencia", label: "Comunidad de Valencia", geoId: 15 },
        { id: "extremadura", label: "Extremadura", geoId: 16 },
        { id: "galicia", label: "Galicia", geoId: 17 },
        { id: "islas_baleares", label: "Islas Baleares", geoId: 8743 },
        { id: "islas_canarias", label: "Islas Canarias", geoId: 8742 },
        { id: "la_rioja", label: "La Rioja", geoId: 20},
        { id: "regios_murcia", label: "Región de Murcia", geoId: 21 },
    ]},
]

export const TIME_TRUNCS: any[] = [
    {id: 'day', label: 'DAYS'},
    {id: 'month', label: 'MONTHS'},
    {id: 'year', label: 'YEARS'},
]

export const TECHNOLOGIES: any[] = [
    {id: 'Hidráulica', label: 'HYDRAULIC'},
    {id: 'Nuclear', label: 'NUCLEAR'},
    {id: 'Carbón', label: 'COAL'},
    {id: 'Motores diésel', label: 'DIESEL_ENGINE'},
    {id: 'Turbina de gas', label: 'GAS_TURBINE'},
    {id: 'Turbina de vapor', label: 'STEAM_TURBINE'},
    {id: 'Ciclo combinado', label: 'COMBINED_CYCLE'},
    {id: 'Hidroeólica', label: 'HYDROWIND'},
    {id: 'Eólica', label: 'WIND'},
    {id: 'Solar Photovoltaic', label: 'SOLAR_PHOTOVOLTAIC'},
    {id: 'Solar Thermal"', label: 'SOLAR_THERMAL'},
    {id: 'Other Renewables', label: 'OTHER_RENEWABLES'},
    {id: 'Cogeneration', label: 'COGENERATION'},
    {id: 'Non-Renewable', label: 'NON_RENEWABLE'},
    {id: 'Renewable Waste', label: 'WASTE_RENEWABLE'},
    {id: 'Total Generation', label: 'TOTAL_GENERATION'},
];

export const TYPES: any[] = [
    {id: 'Renovable', label: 'RENOVABLE'},
    {id: 'No-Renovable', label: 'NO_RENEWABLE'},
    {id: 'Generación total', label: 'TOTAL_GENERATION'}
];